name: Main Workflow
on: [push]
jobs:
  build:
    name: Build
    strategy:
      matrix:
        node-version: [14, 16, 17, 18]
    runs-on: ubuntu-latest
    container: node:${{ matrix.node-version }}
    steps:
      - uses: actions/checkout@v1
      - run: node --version
      - run: ./build.sh
